#:kivy 1.0


<DocumentMenu>:
	orientation: 'tb-lr'
	test:test1
	Button:
		id: test1
		text: 'Find File'
		size_hint_x: 1
		size_hint_y: 0.075
		on_press: root.call_button()
	Button:
		text: '.Doc To Text'
		size_hint_x: 1
		size_hint_y: 0.075
	Button:
		text: '.Doc to .Html'
		size_hint_x: 1
		size_hint_y: 0.075
	Button:
		text: 'Compress Files'
		size_hint_x: 1
		size_hint_y: 0.075
	Button:
		text: 'Hiden Files'
		size_hint_x: 1
		size_hint_y: 0.075 
