
<PictureMenu>:
	orientation: 'tb-lr'
	Button:
		text: 'Find File'
		size_hint_x: 1
		size_hint_y: 0.075
	Button:
		text: 'Add Photo To Album'
		size_hint_x: 1
		size_hint_y: 0.075
	Button:
		text: 'Resize Photo'
		size_hint_x: 1
		size_hint_y: 0.075
	Button:
		text: 'Crop Image'
		size_hint_x: 1
		size_hint_y: 0.075
	Button:
		text: 'Rename File'
		size_hint_x: 1
		size_hint_y: 0.075
	Button:
		text: 'Chang File Type'
		size_hint_x: 1
		size_hint_y: 0.075
		
		
		
