<MusicMenu>:
	orientation: 'tb-lr'
	Button: 
		text: 'Find File'
		background_normal: '../sdcn/data/images/icon5.png'
		size_hint_x: 1
		size_hint_y: None
		size:(1,40)
		on_press: root.add_to_workflow_layout(self)
	Button:
		text: 'Convert Music Type'
		background_normal: '../sdcn/data/images/icon5.png'
		size_hint_x: 1
		size_hint_y: None
		size:(1,40)
		on_press: root.add_to_workflow_layout(self)