#:kivy 1.0

<pdfMenu>:
	orientation:  'tb-lr'
	Button:
		text: 'Find File'
		background_normal: '../sdcn/data/images/icon6.png'
		size_hint_x: 1
		size_hint_y: None
		size:(1,40)
		on_press: root.add_to_workflow_layout(self)
	Button:
		text: 'Convert PDF File'
		background_normal: '../sdcn/data/images/icon6.png'
		size_hint_x: 1
		size_hint_y: None
		size:(1,40)
		on_press: root.add_to_workflow_layout(self)		