<ConvertFile>:
	size_hint: (None,None)
	size: (1,100)
	Label:
		id: workflow_header
		text: 'Convert Files'
		size_hint:(0.89,0.5)
	Button:
		text: 'X'
		size_hint:(0.1,0.3)
		on_press: root.delete_in_workflow_layout(root)
		
	Spinner:
		id: type
		text: '.doc to Text'
		values: ('.doc to Text','.doc to HTML')
		size_hint: (0.5,0.5)
		size:  (1,44)
	Label:
		text: 'to:'
		size_hint: (0.25,.5)
	TextInput:
		id: output
		size_hint: (.25,0.5)
		multiline: False