<CropImage>:
	size_hint: (None,None)
	size:(1,100)
	Label:
		id: workflow_header
		text: 'Crop Image'
		size_hint:(0.89,0.5)
	Button:
		text: 'X'
		size_hint:(0.1,0.3)
		on_press: root.delete_in_workflow_layout(root)
	Label:
		text: 'X'
		size_hint:(0.15,0.15)
	TextInput:
		multiline: False
		size_hint: (0.3,0.3)
	Label:
		text: 'Y'
		size_hint:(0.15,0.15)
	TextInput:
		multiline: False
		size_hint: (0.3,0.3)