<HiddenFile>:
	size_hint: (None,None)
	size: (0.5,100)
	canvas.before:
        Rectangle:
        	source: '../sdcn/data/images/gray1.png'
            pos: self.pos
            size: self.size
	Label:
		id: workflow_header
		text: 'Hidden Files'
		size_hint:(0.89,0.5)
		canvas.before:
			Rectangle:
				source: '../sdcn/data/images/gray2.png'
				pos: self.pos
            	size: self.size
	Button:
		text: 'X'
		size_hint:(0.1,0.5)
		on_press: root.delete_in_workflow_layout(root)