<MyFilechooser>:
	pop: _pop
	id: _pop
	cancel_button: _cancel
	ok: _ok
	filechooser: _filechooser
	StackLayout:
		orientation: 'lr-bt'
		FileChooserIconView:
			id: _filechooser
			size_hint: (0.75,1)
			path:'~/'
		Button:
			id: _ok
			text: 'Ok'
			size_hint: (0.12,None)
			size: (1,25)
			on_press: root.okfile()
		Button:
			id: _cancel
			text: 'Cancel'
			size_hint: (0.12,None)
			size: (1,25)
			on_press: root.cancels()